name: BookStore-fe - Dev
on:
  push:
    branches: [main]
jobs:
  build-and-push-to-docker-hub:
    timeout-minutes: 12
    runs-on: ubuntu-latest
    env:
      GH_VERSION: dev-${{github.sha}}
      GH_VERSION_TAG: dev
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      KUBECTL_VERSION: v1.21.2
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Set up latest LTS Node.js with latest npm
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'  # optional, improves CI performance

      - name: Install dependancies & and build for production
        run: npm install
        run: npm run build:staging
      - name: Build Docker image
        run: |
          docker build -t mwakazi/bookstore-fe:${{ env.GH_VERSION_TAG }} .
      - name: Docker tag
        run: |
          docker tag mwakazi/bookstore-fe:${{ env.GH_VERSION_TAG }} mwakazi/bookstore-fe:${{ env.GH_VERSION }}
      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push mwakazi/bookstore-fe:${{ env.GH_VERSION }}
          docker push mwakazi/bookstore-fe:${{ env.GH_VERSION_TAG }}

  # rollout-to-k8s:
  #   runs-on: self-hosted
  #   needs: build-and-push-to-docker-hub
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Setup kubeconfig
  #       run: |
  #         mkdir -p ~/.kube
  #         echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
  #         chmod 600 ~/.kube/config

  #     - name: Set new image on deployment
  #       run: |
  #         kubectl rollout restart deployment/bookstore-fe --namespace=bookstore-dev
  #     - name: Rollout status
  #       run: |
  #         kubectl rollout status deployment/bookstore-fe --namespace=bookstore-dev